### ISSUE TITLE
my suggestion to keep deadline

### ISSUE THREAD

**Issue by josohany** [mobilecom21/ReactNative-Crypto-#1]
Thank you again.
So you want to finish this job within 2~3 weeks and I reviewed project scope. It is big and I need to work with my friends(graphic designer and api developer). So I can meet your deadline.
But we should be paid via upwork and in case working rate should be high. 
So my hourly rate for this project will be $200.
Please let me know your thought.

**Comment by mobilecom21** [comment]
I understand.
I will it. I hope you to keep my deadline as well as high quality.
